import './globals.css'

export const metadata = {
  title: 'Designed for Impact | Victoria Alli-Johnson',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center justify-center relative">{children}</body>
    </html>
  )
}
