export const metadata = {
  title: 'Portfolio | Designing for Impact | Victoria Alli-Johnson',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" flex flex-col items-center bodyW justify-center relative">{children}</body>
    </html>
  )
}
